bucket_name = "ccproject1"
google_compute_instance = "e2-micro"
project_id = "terraformprovisio0810"
storage_class = "REGIONAL"
image = "gcr.io/terraformprovisio0810/travel-management:latest"
google_compute_instance_location = "us-central1-a"
google_compute_instance_name = "projectprovision"